[docs] Update on containerd pre requisites
openshift/windows-machine-config-operator pull request #1042
Opened 2022-04-29 02:35 UTC by selansen

Update containerd pre requisites information. As WMCO installs and
manages containerd runtime, it is recommanded not to install by user.

Signed-off-by: selansen <esiva@redhat.com>

2022-04-29 13:37 UTC, alinaryan reviewed
spelling nits:

2022-04-29 13:37 UTC, alinaryan commented on README.md
> +it is recommanded not to preinstall containerd in Machineset or BYOH Windows instances.
s/recommanded/recommended/

2022-04-29 13:37 UTC, alinaryan commented on README.md
> +it is recommanded not to preinstall containerd in Machineset or BYOH Windows instances.
s/Machineset/MachineSet/

2022-04-29 14:35 UTC, sebsoto requested changes

2022-04-29 14:35 UTC, sebsoto commented on README.md
> +Windows instances brought up with WMCO are set up with the containerd container runtime. As WMCO installs and manages runtime,
and manages runtime -> and manages the container runtime

2022-04-29 20:44 UTC, alinaryan commented
/lgtm

2022-04-29 21:17 UTC, selansen commented
/hold cancel

2022-04-29 21:20 UTC, merged

2022-05-02 16:55 UTC, selansen commented
cc : @mburke5678

2022-05-04 19:08 UTC, mansikulkarni96 commented
/cherry-pick community-4.10

2022-05-06 19:47 UTC, mansikulkarni96 commented
/cherry-pick community-4.10