[wmco] Enable generation of custom service CMs
openshift/windows-machine-config-operator pull request #1071
Opened 2022-05-16 22:07 UTC by sebsoto

This commit adds the function GenerateWithData which allows for the
creation of service ConfigMaps with custom file and Windows service
specifications. This will be helpful for testing.

2022-05-16 22:09 UTC, sebsoto commented
/approve cancel

2022-05-17 13:25 UTC, selansen commented
/lgtm

2022-05-17 14:04 UTC, saifshaikh48 requested changes

2022-05-17 14:04 UTC, saifshaikh48 commented on pkg/servicescm/servicescm.go
> +func (cmData *data) ValidateRequiredContent() error {
Please update the function doc to reflect the parameter changes.

2022-05-17 16:04 UTC, sebsoto commented
/hold

2022-05-18 13:23 UTC, saifshaikh48 reviewed
/lgtm

2022-05-18 13:37 UTC, selansen commented
/approve

2022-05-18 16:37 UTC, jrvaldes commented on test/e2e/validation_test.go
> +		if err != nil || data.ValidateRequiredContent() != nil {
Looks like  `data.ValidateRequiredContent()` should be part of `servicescm.Parse(...)`. Thoughts?

2022-05-18 16:39 UTC, jrvaldes commented
LGTM, @sebsoto  feel free to remove the hold once you review the comments. 

/hold

2022-05-18 16:51 UTC, sebsoto commented
/hold cancel

2022-05-18 16:53 UTC, merged