Bug 1875530: Fix file transfer when files are already present
openshift/windows-machine-config-operator pull request #115
Opened 2020-09-17 22:09 UTC by ravisantoshgudimetla

I think reproducing via test case is hard as the Window is small.

2020-09-17 22:10 UTC, ravisantoshgudimetla commented
/approve cancel

2020-09-18 14:37 UTC, sebsoto requested changes

2020-09-18 15:48 UTC, sebsoto commented on pkg/controller/windowsmachine/windows/windows.go
> +			continue
Nevermind, no easy way to do this

2020-09-18 16:24 UTC, aravindhp commented
Folded into https://github.com/openshift/windows-machine-config-operator/pull/113

2020-09-18 16:24 UTC, closed without merging