Log WMCO timestamps in RFC3339 format
openshift/windows-machine-config-operator pull request #1168
Opened 2022-08-08 16:22 UTC by sebsoto

Makes timestamps human readable for easier use

2022-08-08 16:28 UTC, sebsoto commented
/approve cancel

2022-08-08 19:54 UTC, sebsoto commented
Example logs with new timestamp format: 
```
2022-08-08T17:53:39Z	INFO	Starting EventSource	{"controller": "certificatesigningrequest", "controllerGroup": "certificates.k8s.io", "controllerKind": "CertificateSigningRequest", "source": "kind source: *v1.Secret"}
2022-08-08T17:53:39Z	INFO	Starting EventSource	{"controller": "certificatesigningrequest", "controllerGroup": "certificates.k8s.io", "controllerKind": "CertificateSigningRequest", "source": "kind source: *v1.Secret"}
```

2022-08-09 13:18 UTC, jrvaldes approved these changes
/lgtm

2022-08-09 14:26 UTC, saifshaikh48 commented
/lgtm

2022-08-09 14:59 UTC, mansikulkarni96 commented
/lgtm 
Thanks for working on the improvement @sebsoto

2022-08-09 19:03 UTC, aravindhp requested changes
Nice improvement, @sebsoto.

2022-08-09 19:03 UTC, aravindhp commented on go.mod
> -	go.uber.org/zap v1.19.1 // indirect
If this was done due to a go mod update, please add the command you ran to the commit message.

2022-08-10 17:03 UTC, aravindhp approved these changes

2022-08-10 17:25 UTC, alinaryan commented
/lgtm

2022-08-10 20:40 UTC, merged