[docs] Clarify storage support
openshift/windows-machine-config-operator pull request #1188
Opened 2022-08-17 17:56 UTC by alinaryan

Adds a supported storage section to our docs that specifies that
only in-tree storage methods are supported in each cloud platform.

2022-08-17 18:09 UTC, Anandnatraj commented
I would change the word "used" to "supported". Otherwise LGTM

2022-08-17 18:20 UTC, Anandnatraj commented
LGTM

2022-08-17 19:38 UTC, aravindhp requested changes
Thanks for adding this, @alinaryan

2022-08-17 19:38 UTC, aravindhp commented on docs/wmco-prerequisites.md
> +## Supported Storage
This is not a pre-requisite but a limitation. I suggest adding a `Storage` sub-section under [limitations](https://github.com/openshift/windows-machine-config-operator#limitations)

2022-08-17 19:46 UTC, aravindhp commented
/cc @mburke5678

2022-08-17 19:47 UTC, aravindhp approved these changes

2022-08-17 19:50 UTC, mansikulkarni96 commented
Thanks for adding this @alinaryan 
/lgtm

2022-08-17 19:50 UTC, mburke5678 approved these changes
/lgtm

2022-08-17 19:56 UTC, merged

2022-08-24 17:19 UTC, alinaryan commented
/cherry-pick release-4.8

2022-08-24 17:19 UTC, alinaryan commented
/cherry-pick release-4.9

2022-08-24 17:20 UTC, alinaryan commented
/cherry-pick release-4.10

2022-08-24 17:20 UTC, alinaryan commented
/cherry-pick release-4.11

2022-08-24 17:20 UTC, alinaryan commented
/cherry-pick release-4.12