[release-4.9] [windows] Increase kubelet verbosity in debug
openshift/windows-machine-config-operator pull request #1303
Opened 2022-11-01 13:34 UTC by jrvaldes

This is manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1198

2022-11-01 18:09 UTC, saifshaikh48 reviewed
/lgtm

2022-11-02 21:38 UTC, aravindhp requested changes

2022-11-02 21:38 UTC, aravindhp commented on pkg/windows/windows.go
> +	// check log level and increase kubelet verbosity accordingly
Please add a new line before the comment to be consistent with the code in master

2022-11-04 14:28 UTC, saifshaikh48 commented
/lgtm

2022-11-08 00:21 UTC, jrvaldes commented
/retest-required

2022-11-08 15:13 UTC, sebsoto commented
/approve

2022-11-08 15:23 UTC, merged

2022-11-17 15:54 UTC, jrvaldes commented
/cherry-pick release-4.8