[pkg] set kubelet priority flag
openshift/windows-machine-config-operator pull request #1555
Opened 2023-04-12 20:48 UTC by alinaryan

Uses the kubelet priority flag introduced in https://github.com/kubernetes/kubernetes/pull/96051 to set the kubelet priority class to ABOVE_NORMAL_PRIORITY_CLASS to ensure that running Pods do not starve the kubelet of CPU cycles.

2023-04-13 13:06 UTC, alinaryan commented
/test all

2023-04-13 18:49 UTC, alinaryan commented
Confirmed process priority was set appropriately on a Windows node using this WMCO image 

![Screenshot from 2023-04-13 14-47-33](https://user-images.githubusercontent.com/66272285/231854675-2dae34e4-77e1-4e20-8363-ac24d4f1efa6.png)

2023-04-13 18:52 UTC, aravindhp commented
> Confirmed process priority was set appropriately on a Windows node using this WMCO image
> 
> ![Screenshot from 2023-04-13 14-47-33](https://user-images.githubusercontent.com/66272285/231854675-2dae34e4-77e1-4e20-8363-ac24d4f1efa6.png)

Shouldn't this be an e2e test?

2023-04-13 18:54 UTC, aravindhp requested changes
Thanks for working on this, @alinaryan. Like I mentioned in the comment, this requires an e2e test.

2023-04-13 18:54 UTC, aravindhp commented on pkg/services/services.go
> +	windowsPriorityClass := "ABOVE_NORMAL_PRIORITY_CLASS"
Please link to the doc about Windows priority classes here.

2023-04-19 17:11 UTC, alinaryan commented
/test all

2023-04-19 19:03 UTC, saifshaikh48 commented on test/e2e/validation_test.go
> +	t.Run("nodes", func(t *testing.T) {
consider moving this into the for loop so a separate test is executed for each node (and you can name each test with the node name)

2023-04-19 19:03 UTC, saifshaikh48 commented on test/e2e/validation_test.go
> +			require.Containsf(t, out, requiredPriorityClass, "node %s missing required kubelet priority class",
This should be an assert. require will prevent other tests from running after, if something were to fail

2023-04-20 15:07 UTC, sebsoto requested changes

2023-04-20 15:07 UTC, sebsoto commented on test/e2e/validation_test.go
> +	out, err := tc.runPowerShellSSHJob("kubelet-query", command, addr)
Please dont name this the same as other jobs in the tests. That makes figuring out the correct pod log to check hard.

lets be specific here, something like "kubelet-priority-class-query"

2023-04-25 14:13 UTC, saifshaikh48 commented on test/e2e/validation_test.go
> +		t.Run("nodes", func(t *testing.T) {
> you can name each test with the node name

e.g. `node.Name` instead of `"nodes"`

2023-04-25 14:13 UTC, saifshaikh48 commented on test/e2e/validation_test.go
> +	}
Should we skip in this case? Elsewhere in the test suite we `require` > 0 nodes
e.g. 
- require.Greater(t, len(gc.allNodes()), 0, "test requires at least one Windows node to run")
- require.NotEmpty(t, gc.allNodes())

2023-04-25 14:37 UTC, mansikulkarni96 commented
LGTM

2023-04-26 17:19 UTC, aravindhp commented
/retitle WINC-561: Set kubelet priority flag

2023-04-26 17:28 UTC, aravindhp reviewed
Nice work, @alinaryan. Just a couple of name change requests.

2023-04-26 17:28 UTC, aravindhp commented on test/e2e/create_test.go
> +	t.Run("Kubelet validation", testKubeletPriority)
Please rename to `Kubelet priority class validation`.

2023-04-26 17:28 UTC, aravindhp commented on test/e2e/validation_test.go
> +func testKubeletPriority(t *testing.T) {
Please rename to `testKubeletPriorityClass`

2023-04-26 17:41 UTC, aravindhp reviewed
/lgtm

2023-04-26 18:22 UTC, sebsoto approved these changes

2023-04-26 19:13 UTC, alinaryan commented
/cherry-pick release-4.13

2023-04-26 19:13 UTC, alinaryan commented
/cherry-pick release-4.12

2023-04-26 19:13 UTC, alinaryan commented
/cherry-pick release-4.10

2023-04-27 20:29 UTC, alinaryan commented
/test azure-e2e-operator

cpu usage err

`error: Query '${t_install} cluster:usage:cpu:install:seconds:quantile    label_replace(quantile_over_time(.95,sum(irate(container_cpu_usage_seconds_total{id="/"}[90s:30s]))[${d_all}:${d_test}]),"quantile","0.95","","")' was not valid: d_test: unbound variable`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1555/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1651291550447046656

2023-04-28 02:52 UTC, merged