[wmco] Refactor Windows service start/creation
openshift/windows-machine-config-operator pull request #157
Opened 2020-11-02 18:13 UTC by saifshaikh48

This change was made to reduce code duplication in the creation and start of Windows services, as well as when checking if a particular file exists on the VM. This makes it easier when adding new services into Windows VM configuration.

2020-11-02 20:39 UTC, aravindhp requested changes

2020-11-02 20:39 UTC, aravindhp commented on pkg/controller/windowsmachine/windows/windows.go
> +			path, vm.ID(), out)
No need to return `out` in the error. I will be logging that error in #147 and that should suffice.

2020-11-03 12:44 UTC, LorbusChris commented
/approve
I suggest we merge this asap so I can easily base further windows_exporter work on top.

2020-11-03 17:30 UTC, aravindhp approved these changes
/approve

Thanks for working on this, @saifshaikh48

2020-11-03 17:48 UTC, LorbusChris commented
/lgtm

2020-11-03 19:29 UTC, sebsoto commented
/lgtm

2020-11-03 23:23 UTC, merged