[release-4.13] CSI proxy cherrypick
openshift/windows-machine-config-operator pull request #1709
Opened 2023-07-28 15:01 UTC by wgahnagl

[[submodule] Add csi-proxy](https://github.com/openshift/windows-machine-config-operator/commit/a846321905d81d6d03b69e4ba8cbb0ebab40810d) 
[[services] Add csi-proxy to Windows service CM](https://github.com/openshift/windows-machine-config-operator/commit/41a3224c7107b832f44015f725049b96f8ba03d5)
[[test] Add vSphere storage testing](https://github.com/openshift/windows-machine-config-operator/commit/c051f8ec1047a5be65df0cd7bb0fde1db3fc70c0)

2023-07-28 15:33 UTC, sebsoto approved these changes
Good work, left a comment, you probably can just remove all changes with the test suite. But you should rerun the e2e tests locally and see if that ends up working as expected.

2023-07-28 17:06 UTC, wgahnagl commented on test/e2e/providers/vsphere/vsphere.go
> +	"reflect"
do you mean tremove all of the e2e tests for the 4.13 version?

2023-07-28 17:58 UTC, jrvaldes requested changes
@wgahnagl  Seems this is a manual backport for:
- https://github.com/openshift/windows-machine-config-operator/pull/1530

Please reflect that in the description of the PR. For example: "Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1530"


In addition, consider adding the `-x` flag while cherry-picking the commits so that the original hash is included in the footer of the commit message.

2023-07-28 18:04 UTC, wgahnagl commented
/hold

2023-07-28 18:06 UTC, sebsoto commented on test/e2e/providers/vsphere/vsphere.go
> +	"reflect"
Not all of the e2e tests. The test changes introduced in this PR.

2023-07-28 18:11 UTC, wgahnagl commented on test/e2e/providers/vsphere/vsphere.go
> +	"reflect"
sorry, I mean should I drop [this commit](737bec68e4ed7fc96aa8657b33fa3baa1686fce6) ?

2023-08-08 16:14 UTC, jrvaldes commented
/lgtm

2023-08-08 16:19 UTC, mtnbikenc commented
/hold cancel

2023-08-08 21:19 UTC, jrvaldes commented
/close 

in favor of https://github.com/openshift/windows-machine-config-operator/pull/1721

2023-08-08 21:19 UTC, closed without merging