Revert "[nodeconfig] Ensure cached WICD creds are set"
openshift/windows-machine-config-operator pull request #1759
Opened 2023-08-29 20:01 UTC by alinaryan

This reverts commit e8839a128ed9dce8c202468d088ba629e8c7b89b.

2023-08-29 20:05 UTC, aravindhp requested changes
Please mention why we are reverting

2023-08-29 20:08 UTC, sebsoto commented on pkg/nodeconfig/nodeconfig.go
> -	if nodeConfigCache.credentials == nil {
Please add to the PR description why this needs to be reverted

2023-08-29 20:50 UTC, saifshaikh48 commented
/lgtm

2023-08-29 21:32 UTC, jrvaldes approved these changes
/lgtm

2023-08-30 14:00 UTC, wgahnagl commented
should this have a [release-4.12] tag?

2023-08-30 14:03 UTC, wgahnagl commented
/lgtm

2023-08-30 16:46 UTC, merged