[release-4.6] Update to Go 1.15 and k8s openshift-4.6
openshift/windows-machine-config-operator pull request #180
Opened 2020-11-17 14:10 UTC by LorbusChris

Backports https://github.com/openshift/windows-machine-config-operator/pull/168 and https://github.com/openshift/windows-machine-config-operator/pull/179 to release-4.6 branch.

2020-11-17 14:37 UTC, aravindhp commented
I would rather not have a PR that is moving to Go 1.15 also adding a bug fix.

2020-11-17 15:24 UTC, aravindhp requested changes
Same comments here https://github.com/openshift/windows-machine-config-operator/pull/179#pullrequestreview-532420483 https://github.com/openshift/windows-machine-config-operator/pull/179#discussion_r525196810 here

2020-11-17 21:36 UTC, LorbusChris commented
/hold
until #179 and #182 have merged. Will rebase after #182.

2020-11-24 16:37 UTC, aravindhp commented on build/Dockerfile.ci
> +FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.6 as build
@LorbusChris please check with ART if they will be updating this image too. If they are not please open a ticket requesting them to do so.

2020-11-26 18:44 UTC, LorbusChris commented
`registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.6` now contains Go 1.15.2. I've updated the PR

2020-11-26 21:58 UTC, LorbusChris commented
/hold cancel

2020-11-27 15:51 UTC, aravindhp approved these changes
/lgtm

2020-11-27 15:53 UTC, merged