[release-4.13] WINC-1098: Block upgrades when migrating from in-tree to CSI
openshift/windows-machine-config-operator pull request #1840
Opened 2023-09-27 19:58 UTC by sebsoto

Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1794

2023-09-27 19:58 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-09-27 19:58 UTC, sebsoto commented
/test aws-e2e-operator

2023-09-27 19:58 UTC, sebsoto commented
/approve cancel

2023-10-03 21:02 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-10-03 23:01 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-10-04 13:45 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-10-04 13:58 UTC, mansikulkarni96 commented
@sebsoto does this need to be backported to 4.12?

2023-10-04 14:53 UTC, sebsoto commented
@mansikulkarni96 No it does not

2023-10-04 19:22 UTC, aravindhp requested changes
Thanks for working on this, @sebsoto

2023-10-04 19:22 UTC, aravindhp commented on controllers/controllers.go
> +	var nodeStats stats.Summary
Please move this closer to the scope where it is used

2023-10-04 19:22 UTC, aravindhp commented on controllers/controllers.go
> +	for _, pod := range nodeSummary.Pods {
If you care only about `nodeSummary.Pods` then there is no need to pass the whole object.

2023-10-04 19:22 UTC, aravindhp commented on controllers/controllers.go
> +func (r *instanceReconciler) getNodeSummary(nodeName string) (stats.Summary, error) {
I suggest just returning `stats.Summary.Pods` given that is all we need and rename the function appropriately. Example: `getPodStatsForNode()`.

2023-10-04 20:14 UTC, saifshaikh48 reviewed
/lgtm

Can re-apply LGTM when other comments are addressed

2023-10-05 13:08 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-10-05 14:08 UTC, saifshaikh48 reviewed
/lgtm

2023-10-05 14:20 UTC, aravindhp approved these changes

2023-10-05 16:53 UTC, mansikulkarni96 commented
/lgtm

2023-10-05 17:23 UTC, sebsoto commented
/test azure-e2e-upgrade

2023-10-05 17:45 UTC, alinaryan reviewed
just a nit: otherwise lgtm

2023-10-05 17:45 UTC, alinaryan commented on controllers/controllers.go
> +		return nil, err
can you add an err msg

2023-10-05 20:24 UTC, merged