[release-4.12] Submodule update 11/16
openshift/windows-machine-config-operator pull request #1947
Opened 2023-11-16 13:38 UTC by sebsoto

2023-11-16 14:06 UTC, sebsoto commented
Dropping
[[vendor] Use v1.25.14+a52e8df k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/pull/1947/commits/7e5e6f32ee3c5dbe8b05d2d03562a84ea1582260) as it is causing a build error

2023-11-16 14:07 UTC, sebsoto commented
/approve cancel

2023-11-16 17:02 UTC, aravindhp commented
> Dropping [[vendor] Use v1.25.14+a52e8df k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/pull/1947/commits/7e5e6f32ee3c5dbe8b05d2d03562a84ea1582260) as it is causing a build error

@sebsoto is that right move? Shouldn't you be fixing the build?

2023-11-16 17:07 UTC, sebsoto commented
@aravindhp I dropped it considering that the goal of this PR is to pick up the kubelet update.

2023-11-16 17:17 UTC, aravindhp commented
@sebsoto then please call that out and have a follow up Jira ticket to tackle this build failure.

2023-11-16 17:42 UTC, saifshaikh48 commented
/lgtm

2023-11-20 15:53 UTC, jrvaldes commented
/lgtm

2023-11-20 16:41 UTC, aravindhp requested changes

2023-11-20 16:43 UTC, mansikulkarni96 commented on go.mod
> +	k8s.io/client-go v0.26.0-alpha.0
+1

2023-12-01 15:12 UTC, mtnbikenc commented
/jira refresh

2023-12-01 19:07 UTC, aravindhp commented
/test images

2023-12-01 20:07 UTC, sebsoto commented
/test remaining-required

2023-12-01 20:13 UTC, aravindhp commented
> /retest-required
> 
> looks like `remaining-required` is not happy here.

@jmguzik any idea what is going on here?

2023-12-01 20:14 UTC, aravindhp commented
Oh wait, did we enable the 2-staged pipelines for release-4.12?

2023-12-01 21:23 UTC, mansikulkarni96 commented
/approve

2023-12-01 23:16 UTC, sebsoto commented
/override ci/prow/security

2023-12-01 23:24 UTC, sebsoto commented
/test remaining-required

2023-12-01 23:25 UTC, sebsoto commented
/test nutanix-e2e-operator vsphere-proxy-e2e-operator

2023-12-01 23:31 UTC, sebsoto commented
/override ci/prow/nutanix-e2e-operator ci/prow/vsphere-proxy-e2e-operator

2023-12-02 01:13 UTC, sebsoto commented
/test platform-none-vsphere-e2e-operator

2023-12-02 03:30 UTC, aravindhp commented
/retest-required

2023-12-03 20:40 UTC, merged