Improve logging for malformed RBAC reconciliation and use context for WICD rbac operations
openshift/windows-machine-config-operator pull request #2166
Opened 2024-05-08 16:16 UTC by jrvaldes

This PR use context for WICD rbac operations and adds a setup log to show the namespace where the operator is running and expands the details
on the malformed RBAC resources reconciliation. 

**before:**
```
2024-05-08T15:51:54Z	INFO	version	operator	{"version": "10.16.0-53d7bda"}
2024-05-08T15:51:54Z	INFO	version	go	{"version": "go1.21.3 linux/amd64"}
2024-05-08T15:51:54Z	INFO	leader	Trying to become the leader.
2024-05-08T15:51:54Z	DEBUG	leader	Found podname	{"Pod.Name": "windows-machine-config-operator-fcdbdb656-xvkkr"}
2024-05-08T15:51:54Z	DEBUG	leader	Found Pod	{"Pod.Namespace": "windows-operator-one", "Pod.Name": "windows-machine-config-operator-fcdbdb656-xvkkr"}
2024-05-08T15:51:54Z	INFO	leader	No pre-existing lock was found.
2024-05-08T15:51:54Z	INFO	leader	Became the leader.
2024-05-08T15:51:54Z	ERROR	controller.secret	Unable to retrieve private key, please ensure it is created	{"error": "the cache is not started, can not read objects"}
2024-05-08T15:51:54Z	DEBUG	ignition	parsed	{"machineconfig": "rendered-worker-22695463f786ddbf71889e3594a9e7b3", "using ignition version": "3.4.0"}
2024-05-08T15:51:54Z	DEBUG	ignition	processing kubelet-ca	{"ControllerConfig": "machine-config-controller"}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created	{"ConfigMap": {"name":"windows-services-10.16.0-53d7bda","namespace":"windows-operator-one"}}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created resource	{"RoleBinding": {"name":"windows-instance-config-daemon","namespace":"windows-operator-one"}}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Deleted malformed resource	{"ClusterRoleBinding": "windows-instance-config-daemon"}]}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created resource	{"ClusterRoleBinding": "windows-instance-config-daemon"}
2024-05-08T15:51:54Z	INFO	setup	starting manager
```

**after:**
```
2024-05-08T15:51:54Z	INFO	version	operator	{"version": "10.16.0-53d7bda"}
2024-05-08T15:51:54Z	INFO	version	go	{"version": "go1.21.3 linux/amd64"}
2024-05-08T15:51:54Z	INFO	leader	Trying to become the leader.
2024-05-08T15:51:54Z	DEBUG	leader	Found podname	{"Pod.Name": "windows-machine-config-operator-fcdbdb656-xvkkr"}
2024-05-08T15:51:54Z	DEBUG	leader	Found Pod	{"Pod.Namespace": "windows-operator-one", "Pod.Name": "windows-machine-config-operator-fcdbdb656-xvkkr"}
2024-05-08T15:51:54Z	INFO	leader	No pre-existing lock was found.
2024-05-08T15:51:54Z	INFO	leader	Became the leader.
2024-05-08T15:51:54Z	INFO	setup	operator	{"namespace": "windows-operator-one"}
2024-05-08T15:51:54Z	ERROR	controller.secret	Unable to retrieve private key, please ensure it is created	{"error": "the cache is not started, can not read objects"}
2024-05-08T15:51:54Z	DEBUG	ignition	parsed	{"machineconfig": "rendered-worker-22695463f786ddbf71889e3594a9e7b3", "using ignition version": "3.4.0"}
2024-05-08T15:51:54Z	DEBUG	ignition	processing kubelet-ca	{"ControllerConfig": "machine-config-controller"}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created	{"ConfigMap": {"name":"windows-services-10.16.0-53d7bda","namespace":"windows-operator-one"}}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created resource	{"RoleBinding": {"name":"windows-instance-config-daemon","namespace":"windows-operator-one"}}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Deleted malformed resource	{"ClusterRoleBinding": "windows-instance-config-daemon", "RoleRef": "windows-instance-config-daemon", "Subjects": [{"kind":"ServiceAccount","name":"windows-instance-config-daemon","namespace":"openshift-windows-machine-config-operator"}]}
2024-05-08T15:51:54Z	INFO	controllers.configmap	Created resource	{"ClusterRoleBinding": "windows-instance-config-daemon"}
2024-05-08T15:51:54Z	INFO	setup	starting manager
```

**proposed additions:**

 - new  setup log to show the namespace where the operator was installed
- extended controllers.configmap log to include the  RoleRef and Subjects of the malformed resource

```
...
2024-05-08T15:51:54Z	INFO	setup	operator	{"namespace": "windows-operator-one"}
...
2024-05-08T15:51:54Z	INFO	controllers.configmap	Deleted malformed resource	{"ClusterRoleBinding": "windows-instance-config-daemon", "RoleRef": "windows-instance-config-daemon", "Subjects": [{"kind":"ServiceAccount","name":"windows-instance-config-daemon","namespace":"openshift-windows-machine-config-operator"}]}
...
```

2024-05-08 16:19 UTC, jrvaldes commented
/test vsphere-e2e-operator

2024-05-13 14:43 UTC, mansikulkarni96 commented
@jrvaldes can you add a comment pointing out the difference in logs before and after this change?

2024-05-13 21:50 UTC, jrvaldes commented
/jira refresh

2024-05-13 21:58 UTC, jrvaldes commented
> @jrvaldes can you add a comment pointing out the difference in logs before and after this change?

@mansikulkarni96  I included the requested information in the [description](https://github.com/openshift/windows-machine-config-operator/pull/2166#issue-2285968196) of the PR. PTAL

2024-05-15 13:06 UTC, jrvaldes commented
/test remaining-required

2024-05-15 14:54 UTC, mansikulkarni96 approved these changes

2024-05-15 16:28 UTC, sebsoto requested changes

2024-05-15 18:10 UTC, jrvaldes commented on cmd/operator/main.go
> +	if err := configMapReconciler.EnsureWICDRBAC(ctx); err != nil {
PR reframed. @sebsoto  PTAL

2024-05-15 18:43 UTC, sebsoto commented on cmd/operator/main.go
> +	if err := configMapReconciler.EnsureWICDRBAC(ctx); err != nil {
thanks LGTM

2024-05-15 18:43 UTC, sebsoto commented
/lgtm

2024-05-15 19:37 UTC, merged