[WIP] test
openshift/windows-machine-config-operator pull request #2223
Opened 2024-06-13 17:51 UTC by mansikulkarni96

2024-06-13 17:51 UTC, mansikulkarni96 commented
/test vsphere-disconnected-e2e-operator

2024-06-13 18:38 UTC, mansikulkarni96 commented
/test vsphere-disconnected-e2e-operator

2024-06-14 17:52 UTC, mansikulkarni96 commented
/test aws-e2e-operator

2024-06-14 18:14 UTC, mansikulkarni96 commented
/approve cancel

2024-06-17 15:39 UTC, mansikulkarni96 commented
/test vsphere-disconnected-e2e-operator

2024-06-18 13:11 UTC, sebsoto requested changes

2024-06-18 13:11 UTC, sebsoto commented on test/e2e/network_test.go
> +func (tc *testContext) waitUntilJobSucceedsAndFetchLogs(name string) (string, error) {
I feel this name change is overly verbose. Its a common pattern for functions like this to return logs, having a note in the function doc as you did should be good enough.

2024-06-18 13:37 UTC, sebsoto approved these changes

2024-06-18 17:39 UTC, wgahnagl commented
/lgtm

2024-06-18 17:47 UTC, mansikulkarni96 commented
/test remaining-required

2024-06-19 07:50 UTC, mansikulkarni96 commented
/retest-required

2024-06-20 12:36 UTC, mansikulkarni96 commented
/retest-required

2024-06-21 15:07 UTC, mansikulkarni96 commented
/hold
until vsphere template issue is resolved

2024-06-25 19:50 UTC, saifshaikh48 commented
/retest-required

2024-06-26 15:22 UTC, mansikulkarni96 commented
/retest-required

2024-06-27 13:19 UTC, mansikulkarni96 commented
/retest-required

2024-06-28 15:18 UTC, mansikulkarni96 commented
/retest-required

2024-06-28 15:54 UTC, saifshaikh48 commented
/unhold

vsphere issues should be resolved

2024-06-28 17:18 UTC, mansikulkarni96 commented
/override Red Hat Konflux / windows-machine-config-operator-bundle-master-on-pull-request

2024-06-28 17:22 UTC, mansikulkarni96 commented
/override Red Hat Konflux / windows-machine-config-operator-bundle-master-on-pull-request

2024-06-28 17:23 UTC, mansikulkarni96 commented
/override "Red Hat Konflux / windows-machine-config-operator-bundle-master-on-pull-request"

2024-06-28 17:27 UTC, merged

2024-06-28 18:51 UTC, mansikulkarni96 commented
/cherry-pick release-4.16