[hack] Update WMCO version to 1.0.2
openshift/windows-machine-config-operator pull request #227
Opened 2020-12-14 17:26 UTC by mansikulkarni96

This commit updates the WMCO version to 1.0.2 in hack/common.sh script.

2020-12-14 17:30 UTC, aravindhp approved these changes
/approve

2020-12-14 18:54 UTC, VaishnaviHire commented
/lgtm

2020-12-14 20:11 UTC, VaishnaviHire commented
According to the doc `4.5` index is included as a part of this change. Just want to make sure if that is expected

2020-12-14 20:27 UTC, VaishnaviHire commented
/lgtm

2020-12-15 14:58 UTC, mansikulkarni96 commented
/retest

2020-12-15 16:34 UTC, aravindhp commented
/hold
Until #230 merges

2021-01-08 00:10 UTC, aravindhp requested changes

2021-01-08 00:10 UTC, aravindhp commented on hack/common.sh
> +  OPERATOR_VERSION=1.0.2
At this point we should just update the version to 2.0.0 in master.

2021-01-14 21:21 UTC, closed without merging