Explicitly set GOBIN path for promu installation
openshift/windows-machine-config-operator pull request #254
Opened 2021-01-19 20:23 UTC by mansikulkarni96

This PR creates windows_exporter directory before-hand and explicitly sets the GOBIN path to specify where the promu binary should be installed, promu installed in the windows_exporter directory is then utilized for its installation.
This change was necessary because Cachito integration on CpaaS side changes the GOPATH during image build and if the path is not specified promu is installed to some location from which it is not accessible to build windows_exporter executable.

2021-01-19 20:23 UTC, mansikulkarni96 commented
/cc: @VaishnaviHire

2021-01-19 20:34 UTC, PratikMahajan commented on build/Dockerfile
> +RUN mkdir /build/windows-machine-config-operator/windows_exporter/
the WORKDIR below(L27) basically does `mkdir` and `cd`. 
So this step can be skipped.

2021-01-19 20:44 UTC, PratikMahajan commented on build/Dockerfile
> +RUN export GOBIN=/build/windows-machine-config-operator/windows_exporter/ && go install .
You can remove `export` if `GOBIN` needs to be set only for this command.

2021-01-19 20:53 UTC, PratikMahajan commented on build/Dockerfile
> +RUN mkdir /build/windows-machine-config-operator/windows_exporter/
`go install .` below should create the directory you're passing as `GOBIN`. Is it facing any permission issues on cachito side?

2021-01-19 21:15 UTC, PratikMahajan requested changes

2021-01-19 21:15 UTC, PratikMahajan commented on build/Dockerfile
> +RUN GOBIN=/build/windows-machine-config-operator/windows_exporter/ && go install .
```suggestion
RUN GOBIN=/build/windows-machine-config-operator/windows_exporter/ go install .
```

2021-01-19 21:32 UTC, mansikulkarni96 commented on build/Dockerfile
> +RUN GOBIN=/build/windows-machine-config-operator/windows_exporter/ && go install .
thanks for the catch

2021-01-20 16:34 UTC, aravindhp approved these changes
/approve

2021-01-20 16:40 UTC, sebsoto commented
/lgtm

2021-01-20 16:42 UTC, mansikulkarni96 commented
/test azure-e2e-operator

2021-01-20 23:42 UTC, merged