WIP: support other networking types
openshift/windows-machine-config-operator pull request #445
Opened 2021-05-10 15:50 UTC by lmm

Hi everyone,

This PR is some WIP code that adds support for 3rd-party networking (old issue here: https://github.com/openshift/windows-machine-config-operator/issues/134). I'd like to use this as a starting point for discussion on how we could support other networking types.

The overall flow here is:
- User creates a machineset for their Windows nodes
- On those Windows nodes, the user sets up the networking and install the CNI config and binaries (e.g. Calico).
- WMCO sets up the node but does not configure networking since networking isn't OVN-Kubernetes.
- (One missing bit of code is for WMCO to uncordon the node once it's ready)

I'd love to get some input on this, thanks!

2021-05-10 15:59 UTC, aravindhp commented
/ok-to-test

2021-05-10 19:12 UTC, sebsoto requested changes
A few quick thoughts from skimming this, please rebase as well.

2021-05-11 05:40 UTC, lmm commented on pkg/cluster/config.go
> +	OvnKubernetesNetwork = "OVNKubernetes"
Fixed with https://github.com/openshift/windows-machine-config-operator/pull/445/commits/425816d40ff75d0775efca28b5f2e686040ab995

2021-05-11 05:41 UTC, lmm commented on pkg/cluster/config.go
> +		return &thirdPartyNetworking{
https://github.com/openshift/windows-machine-config-operator/pull/445/commits/932d7b500eeb8ae28bd53862ff6a7847831837f2

2021-05-11 05:42 UTC, lmm commented on pkg/nodeconfig/nodeconfig.go
> +	network.networkType = networkType
https://github.com/openshift/windows-machine-config-operator/pull/445/commits/7cc9e8c13b5b54c79745efb347caa620fbdb7499

2021-11-26 15:52 UTC, closed without merging