[docs] Update README with BYOH removal info
openshift/windows-machine-config-operator pull request #507
Opened 2021-07-08 14:35 UTC by sebsoto

2021-07-08 14:35 UTC, sebsoto commented
/approve cancel

2021-07-08 14:43 UTC, sebsoto commented
/test vsphere-e2e-operator

2021-07-09 16:36 UTC, sebsoto commented
/retest

2021-07-09 18:36 UTC, aravindhp requested changes
Thanks for doing this, @sebsoto

2021-07-09 18:36 UTC, aravindhp commented on README.md
> +to WMCO.
Please provide an example by removing `10.1.42.1`

2021-07-09 18:37 UTC, aravindhp commented
/cc @EricPonvelle

2021-07-09 18:40 UTC, EricPonvelle requested changes
I have one small correction.

2021-07-09 18:40 UTC, EricPonvelle commented on README.md
> +BYOH instances that have been joined to the cluster as a node can be removed by deleting the instance's entry in the
I'm unsure if "joined" is a term, but if it's not, maybe "BYOH instances that are attached to the cluster..."

2021-07-21 20:29 UTC, saifshaikh48 commented
/lgtm

2021-07-21 20:30 UTC, sebsoto commented
/hold

2021-07-22 15:04 UTC, EricPonvelle approved these changes
/lgtm

2021-07-23 17:16 UTC, saifshaikh48 reviewed
/lgtm

2021-07-23 17:19 UTC, aravindhp approved these changes
/approve

2021-07-23 17:50 UTC, sebsoto commented
/hold cancel

2021-07-23 17:50 UTC, merged

2021-08-03 13:32 UTC, sebsoto commented
/cherry-pick community-4.8

2021-08-12 17:55 UTC, mansikulkarni96 commented
/ cherry-pick release-4.8