[e2e] Update golden image template for vSphere
openshift/windows-machine-config-operator pull request #514
Opened 2021-07-12 21:15 UTC by jrvaldes

2021-07-12 22:20 UTC, aravindhp requested changes
Thanks for doing this, @jrvaldes 

Please call out the scenario that caused us to make this change in the PR and commit message.

2021-07-13 18:17 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-13 18:55 UTC, saifshaikh48 commented
/lgtm

Thanks for working on this @jrvaldes

2021-07-13 19:07 UTC, aravindhp approved these changes
Thanks for doing this, @jrvaldes 

/approve

2021-07-13 19:17 UTC, jrvaldes commented
/cherry-pick release-4.8

2021-07-13 19:17 UTC, jrvaldes commented
/cherry-pick community-4.8

2021-07-13 19:18 UTC, jrvaldes commented
/cherry-pick release-4.7

2021-07-13 19:18 UTC, jrvaldes commented
/cherry-pick community-4.7

2021-07-13 19:24 UTC, sebsoto commented
/lgtm

2021-07-14 02:09 UTC, aravindhp commented
/hold

Until we can figure out why the node doesn't come up

2021-07-14 19:30 UTC, aravindhp commented
/retest

2021-07-15 06:18 UTC, aravindhp commented
/retest

2021-07-16 05:29 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-16 13:39 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-16 18:35 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-16 20:35 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-16 23:12 UTC, aravindhp commented
/lgtm
/hold cancel

2021-07-16 23:13 UTC, merged

2021-07-16 23:21 UTC, aravindhp commented
> @jrvaldes: #514 failed to apply on top of branch "release-4.7":
> 
> ```
> Applying: Update golden image template for vSphere
> Using index info to reconstruct a base tree...
> M	test/e2e/providers/vsphere/vsphere.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/providers/vsphere/vsphere.go
> CONFLICT (content): Merge conflict in test/e2e/providers/vsphere/vsphere.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Update golden image template for vSphere
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

@jrvaldes please manually backport to release-4.7