[e2e] Update golden image template for vSphere
openshift/windows-machine-config-operator pull request #538
Opened 2021-07-23 15:46 UTC by jrvaldes

cherry picked from commit 820507d
cherry picked from commit df8b7de

2021-07-23 16:01 UTC, aravindhp approved these changes
/approve

2021-07-23 17:12 UTC, aravindhp commented
/retitle [release-4.7][e2e] Update golden image template for vSphere

2021-07-23 20:12 UTC, jrvaldes commented
/test azure-e2e-operator

2021-07-27 14:52 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-07-27 20:50 UTC, jrvaldes commented
/test vsphere-e2e-operator

retest due to network issues.

2021-07-28 13:00 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-08-19 02:49 UTC, aravindhp commented
/approve cancel

@jrvaldes please do not mass backport unrelated commits

2021-08-19 14:36 UTC, jrvaldes commented
> /approve cancel
> 
> @jrvaldes please do not mass backport unrelated commits

The goal is to bring https://github.com/openshift/windows-machine-config-operator/commit/6fcb30f527b499fd3d6ddc0550d38aaa68ae760e , since auto cherry-picking [failed](https://github.com/openshift/windows-machine-config-operator/pull/544#issuecomment-897889392). Good catch, dropped the [unrelated commit](https://github.com/openshift/windows-machine-config-operator/commit/fa141f2b401a4a81963194239b0d095ed258693f), I was testing locally with it and got pushed by mistake.

2021-08-19 16:42 UTC, aravindhp commented
> > /approve cancel
> > @jrvaldes please do not mass backport unrelated commits
> 
> The goal is to bring [6fcb30f](https://github.com/openshift/windows-machine-config-operator/commit/6fcb30f527b499fd3d6ddc0550d38aaa68ae760e) , since auto cherry-picking [failed](https://github.com/openshift/windows-machine-config-operator/pull/544#issuecomment-897889392).

Do you know why the auto cherry-pick failed? Is it because you are doing out of order cherry-picking? Please ensure all the required changes are being back ported in the correct order.

2021-09-17 18:42 UTC, jrvaldes commented
/test vsphere-e2e-operator

https://github.com/openshift/windows-machine-config-operator/pull/614 merged.

2021-09-22 03:19 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-09-22 14:04 UTC, jrvaldes commented
/test vsphere-e2e-operator

timed out waiting for creation

2021-09-23 17:30 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-09-23 18:20 UTC, jrvaldes commented
/test vsphere-e2e-operator

Failed creating infrastructure resources

2021-09-24 15:38 UTC, jrvaldes commented
/test vsphere-e2e-operator

Landed in IBMCloud

2021-09-24 15:40 UTC, aravindhp approved these changes
/approve

2021-09-24 17:44 UTC, aravindhp approved these changes
/lgtm

2021-09-24 19:30 UTC, jrvaldes commented
/test aws-e2e-operator

2021-09-24 19:30 UTC, jrvaldes commented
/test azure-e2e-operator

2021-09-24 19:38 UTC, aravindhp commented
Seeing `E0924 18:45:22.931085       1 actuator.go:57] e2e-wm-p2ccw error: e2e-wm-p2ccw: reconciler failed to Create machine: Permission to perform this operation was denied.` in `vsphere-e2e-operator ` test. ref: [machine-controller log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/538/pull-ci-openshift-windows-machine-config-operator-release-4.7-vsphere-e2e-operator/1441457956649439232/artifacts/vsphere-e2e-operator/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-5778bd4d88-q9kbq_machine-controller.log)

/retest-required

2021-09-25 18:02 UTC, aravindhp commented
/hold

Continuing to see permission issues on IBM cloud cluster
```
E0925 16:08:52.968417       1 actuator.go:57] e2e-wm-bnfbw error: e2e-wm-bnfbw: reconciler failed to Create machine: Permission to perform this operation was denied.
```

2021-09-27 15:26 UTC, aravindhp commented
/hold cancel
/retest

The permission issue on the IBM cluster has been fixed

2021-09-27 21:46 UTC, aravindhp commented
/hold

until we decide if we need to force merge or add the bug fix to this PR

2021-09-27 23:41 UTC, jrvaldes commented
/hold

2021-09-29 14:13 UTC, aravindhp requested changes
As mentioned during the discussion, this PR has to be reframed / retitled so that it is associated with the release-4.7 bug.

2021-09-29 15:51 UTC, jrvaldes commented
/bugzilla refresh

2021-09-29 15:51 UTC, jrvaldes commented
/test vsphere-e2e-operator

2021-09-29 15:54 UTC, aravindhp approved these changes
/approve
/retest

2021-09-29 19:57 UTC, saifshaikh48 commented
/lgtm
/unhold

2021-09-29 20:00 UTC, merged