[wmco] Remove stuttering from instances pkg
openshift/windows-machine-config-operator pull request #572
Opened 2021-08-05 21:51 UTC by aravindhp

- Rename instances pkg to instance
- Rename InstanceInfo to Info
- Rename NewInstanceInfo to NewInfo

This results in more natural names for the types and functions in their call sites.

2021-08-05 21:51 UTC, aravindhp commented
/approve cancel
/cc @openshift/openshift-team-windows-containers

2021-08-06 14:12 UTC, jrvaldes commented
/retest

2021-08-06 14:13 UTC, jrvaldes approved these changes
/lgtm

2021-08-09 13:15 UTC, sebsoto requested changes

2021-08-09 13:15 UTC, sebsoto commented on pkg/instance/instance.go
> +// NewInfo returns a new instanceInfo. newHostname being set means that the instance's hostname should be
`new instanceInfo` -> `new Info`

2021-08-09 18:21 UTC, sebsoto commented
/approve

2021-08-09 18:27 UTC, mansikulkarni96 commented
/lgtm

2021-08-09 18:50 UTC, aravindhp commented
/cherry-pick release-4.8

2021-08-09 18:50 UTC, aravindhp commented
/cherry-pick community-4.8

2021-08-10 01:14 UTC, aravindhp commented
/hold

until https://github.com/openshift/release/pull/21004 merges

2021-08-10 21:22 UTC, aravindhp commented
/hold cancel

https://github.com/openshift/release/pull/21004 has merged

/retest

2021-08-11 05:30 UTC, aravindhp commented
/retest

2021-08-11 15:55 UTC, aravindhp commented
/hold
until we bump the kebelet sub-module to 1.22-rc.0

2021-08-12 14:37 UTC, aravindhp commented
/hold cancel
/retest

2021-08-13 17:42 UTC, merged

2021-08-13 17:43 UTC, aravindhp commented
Seeing a [flake](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/572/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1426165308594327552) with HNS deletions.

2021-08-18 19:16 UTC, mansikulkarni96 commented
/cherry-pick release-4.8