[wmco] Perform DNS lookup on instance address
openshift/windows-machine-config-operator pull request #655
Opened 2021-09-02 14:35 UTC by saifshaikh48

This PR performs checks on a Windows instance's network address.
Instead of using the raw address, it is checked to ensure it is an IPv4
address or if it resolves via DNS lookup. This is needed in case an instance's
DNS address does not match its hostname.

Fixes BZ#1995684

2021-09-02 14:37 UTC, saifshaikh48 commented
/retitle Bug 1995684: Validate and perform DNS lookup on Windows instance network address

2021-09-02 15:23 UTC, sebsoto requested changes

2021-09-02 19:16 UTC, sebsoto commented
/approve

2021-09-02 20:26 UTC, mansikulkarni96 commented
Thanks for working on this @saifshaikh48 
/lgtm

2021-09-02 20:29 UTC, mansikulkarni96 commented
/test vsphere-e2e-operator

2021-09-02 20:29 UTC, mansikulkarni96 commented
/cherry-pick release-4.8

2021-09-02 20:29 UTC, mansikulkarni96 commented
/cherry-pick community-4.8

2021-09-02 22:44 UTC, merged

2021-09-09 15:31 UTC, aravindhp commented
@mansikulkarni96 @saifshaikh48 please follow up and ensure this fix is backported to community-4.8. We most likely missed backporting some other PR causing this backport to fail.

2021-09-09 16:15 UTC, mansikulkarni96 commented
I don't see a conflict locally when cherry-picking on the community-4.8 branch, retrying
/cherry-pick community-4.8