[docs][vsphere-ci] Update WMTools to v11360
openshift/windows-machine-config-operator pull request #692
Opened 2021-09-21 16:47 UTC by jrvaldes

Update the WMware Tools ISO image with newer version in the
build.json script, used by Packer to create the golden image template.

The new WMware Tools ISO image was manually uploaded to vCenter.

[See VMware documentation for release notes](https://docs.vmware.com/en/VMware-Tools/11.3/rn/VMware-Tools-1130-Release-Notes.html)

2021-09-21 18:33 UTC, aravindhp requested changes
Thanks for working on this, @jrvaldes. Please replace `WMTools` with `VMTools` everywhere

2021-09-21 18:35 UTC, aravindhp requested changes
Please mention the official version i.e.  `11.3.0` rather than `v11360` which might be an internal version scheme.

2021-09-21 19:32 UTC, jrvaldes commented
> Thanks for working on this, @jrvaldes. Please replace `WMTools` with `VMTools` everywhere

Fixed in https://github.com/openshift/windows-machine-config-operator/commit/07dba5b518805f27d7708559ca31c9eadd85500a

2021-09-21 22:59 UTC, aravindhp approved these changes
/approve

2021-09-24 01:55 UTC, selansen reviewed
lgtm

2021-09-24 13:25 UTC, saifshaikh48 commented
/lgtm

@selansen btw you'll need the `/` in front of the `lgtm` in order for it to be picked up as a command to the bot. [Full list of commands here](https://prow.k8s.io/command-help)

2021-09-24 13:27 UTC, merged

2021-09-28 17:44 UTC, jrvaldes commented
/cherry-pick release-4.9

2021-09-28 17:44 UTC, jrvaldes commented
/cherry-pick release-4.8

2021-09-28 17:44 UTC, jrvaldes commented
/cherry-pick community-4.8