Add ServiceAccount manifest
openshift/windows-machine-config-operator pull request #803
Opened 2021-11-12 18:08 UTC by Fedosin

When I deploy the operator, I get next error from WMCO deployment:

```txt
error looking up service account openshift-windows-machine-config-operator/windows-machine-config-operator:
      serviceaccount "windows-machine-config-operator" not found'
```

This commit adds a manifest for the missing service account. After that everything installs well.

2021-11-12 19:00 UTC, mansikulkarni96 commented
Thanks for fixing this @Fedosin 
This was removed as part of a service_account duplication manifest issue. Tested it locally, works well as long as we do not add the service account file to the manifests directory that gets created with this when we do `make bundle`

/lgtm

2021-11-14 10:28 UTC, Fedosin commented
/test vsphere-e2e-operator

2021-11-25 11:17 UTC, Fedosin commented
/test vsphere-e2e-operator

2021-11-25 18:10 UTC, aravindhp requested changes
Thanks for fixing this, @Fedosin. Please add a `[config]` prefix to the commit and PR headers.

2021-11-25 18:10 UTC, aravindhp commented on config/rbac/service_account.yaml
> +---
This is only required if you are adding multiple "kinds".

2021-11-29 15:16 UTC, mansikulkarni96 commented
/lgtm

2021-12-15 15:17 UTC, Fedosin commented
/retest

2021-12-16 23:15 UTC, Fedosin commented
/retest

2021-12-17 14:52 UTC, alinaryan commented
/lgtm

2021-12-17 21:36 UTC, Fedosin commented
/retest

2021-12-17 21:52 UTC, selansen commented
/lgtm

2021-12-18 09:42 UTC, Fedosin commented
/retest

2022-01-04 17:40 UTC, sebsoto commented
/approve
As this is manually tested and linting PR is in progress

2022-01-05 00:43 UTC, aravindhp commented
/hold

Azure cluster bring up is consistently failing

2022-01-12 16:16 UTC, sebsoto commented
/retest

2022-01-12 18:50 UTC, sebsoto commented
/hold cancel

2022-01-13 17:00 UTC, aravindhp commented
/hold

until we figure out why the override for the cluster approver is not taking effect causing the CSR validation test to fail

2022-01-18 17:29 UTC, sebsoto commented
/retest

2022-01-19 16:54 UTC, sebsoto commented
/hold cancel

2022-01-19 16:54 UTC, sebsoto commented
/retest

2022-01-20 01:53 UTC, merged